calico_merge_patches:
  - name: "calico-patch1"
    path: "files/calico/calico-patch1.yaml"

nginx_merge_patches:
  - name: "nginx-patch1"
    path: "files/nginx/nginx-patch1.yaml"

k8s_control_static_manifest_patches:
  - name: "kube-apiserver01+merge.yaml"  # target[suffix][+patchtype].extension
    path: "files/manifests/kube-apiserver01+merge.yaml"       # local path to patch
