# Values that have to be configured
k8s_version: ""

k8s_control_first_node: ""
k8s_control_plane_endpoint: ""

k8s_init_extra_options: ""

# Values for which default is set, but can be modified
k8s_ethernet_interface: "default" # default will be replaced using ansible_default_ipv4 otherwise ansible interface name
k8s_pod_network_cidr: "10.10.44.0/20"

# k8s_control_static_manifest_patches:
#   - name: "kube-apiserver0+merge.yaml"  # target[suffix][+patchtype].extension
#     path: "files/apiserver-patch"       # local path to patch

k8s_bin_dir: /usr/bin
k8s_conf_dir: /etc/kubernetes

kubectl: "{{ k8s_bin_dir }}/kubectl --kubeconfig {{ k8s_conf_dir }}/admin.conf"
kubeadm: "{{ k8s_bin_dir }}/kubeadm"

k8s_kernel_modules:
  - br_netfilter

k8s_sysctl_variables:
  - name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
  - name: net.bridge.bridge-nf-call-iptables
    value: "1"
