- name: Check if SELinux mode is valid
  ansible.builtin.assert:
    that: centos_selinux_mode == "permissive" or centos_selinux_mode == "enforcing"
    quiet: true
    msg: 'valid values are "permissive" and "enforcing"'

- name: Enforce SELinux mode now
  ansible.builtin.shell: >
    setenforce {{ 0 if centos_selinux_mode == 'permissive' else 1 }}
  changed_when: false

- name: Persist SELinux mode
  ansible.posix.selinux:
    policy: targeted
    state: "{{ centos_selinux_mode }}"


- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  when: centos_firewall_enabled

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: not centos_firewall_enabled

- name: Enable swap
  block:
    - name: Enable swap
      ansible.builtin.command: swapon -a
      when: ansible_swaptotal_mb == 0

    - name: Enable swap entries in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^# ([^\s]+\s+[^\s]+\s+swap\s+.*)$'
        replace: '\1'
  when: centos_swap_enabled

- name: Disable swap
  block:
    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable swap entries in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^\s]+\s+[^\s]+\s+swap\s+.*)$'
        replace: '# \1'
  when: not centos_swap_enabled
