---
- hosts: localhost
  tasks:
    - include_vars:
        dir: group_vars/k8s_cluster

    - ansible.builtin.add_host:
        name: "{{ k8s_control_first_node }}"
        groups: k8s_control_init

    - ansible.builtin.add_host:
        name: "{{ item }}"
        group: k8s_control_join
      with_items: "{{ groups['k8s_control_plane'] | reject('==', k8s_control_first_node) | list }}"

# Deploy first control node and networking
- hosts: "k8s_control_init"
  become: true
  roles:
    - role: centos
    - role: crio
    - role: kubernetes/node/common
    - role: kubernetes/node/control
    - role: kubernetes/calico

# Deploy additional control nodes
- hosts: k8s_control_join
  become: true
  serial: 1
  roles:
    - role: centos
    - role: crio
    - role: kubernetes/node/common
    - role: kubernetes/node/control

# Deploy worker nodes
- hosts: k8s_node
  become: true
  serial: 1
  roles:
    - role: centos
    - role: crio
    - role: kubernetes/node/common
    - role: kubernetes/node/worker

# Deploy applications
- hosts: k8s_control_init
  become: true
  vars_files:
    - roles/kubernetes/node/common/defaults/main.yaml
  roles:
    - role: kubernetes/nginx
