- hosts: load_balancer
  become: true
  vars:
    haproxy_backend_nodes:
      - name: master1
        address: "192.168.56.11"
        port: "6443"
      - name: master2
        address: "192.168.56.12"
        port: "6443"
  roles:
    - role: centos
    - role: haproxy
