---
- name: Add libcontainers repository
  ansible.builtin.yum_repository:
    name: "kubernetes"
    description: Kubernetes
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch"
    gpgcheck: true
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    exclude:
      - kubelet
      - kubeadm
      - kubectl
    enabled: true

- name: Install tc
  ansible.builtin.dnf:
    name: iproute-tc
    state: present

- name: Install kubeadm
  ansible.builtin.dnf:
    name:
      - "kubeadm-{{ k8s_version }}"
    state: present
    disable_excludes: kubernetes
  when: "'kubeadm' not in ansible_facts.packages"

- name: Install kubelet
  ansible.builtin.dnf:
    name:
      - "kubelet-{{ k8s_version }}"
    state: present
    disable_excludes: kubernetes
  when: "'kubelet' not in ansible_facts.packages"

- name: Install kubectl
  ansible.builtin.dnf:
    name:
      - "kubectl-{{ k8s_version }}"
    state: present
    disable_excludes: kubernetes
  when: "'kubectl' not in ansible_facts.packages"

- name: Modify kubelet configuration
  ansible.builtin.lineinfile:
    path: "/etc/sysconfig/kubelet"
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_facts[k8s_ethernet_interface]['ipv4']['address'] }}"
    regexp: "^KUBELET_EXTRA_ARGS="
    state: present
  when: k8s_ethernet_interface != "default"

- name: Start and enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: true
