---
- name: Gather facts about cluster and node
  ansible.builtin.include_tasks: facts.yaml

- name: Include system configuration tasks
  ansible.builtin.include_tasks: system.yaml

- name: Include install tasks
  ansible.builtin.include_tasks: install.yaml

- name: Include upgrade tasks
  ansible.builtin.include_tasks: upgrade.yaml
