- name: Create conf file to load required kernel modules on boot
  ansible.builtin.template:
    src: "kubernetes_kernel_modules.conf.j2"
    dest: "/etc/modules-load.d/kubernetes.conf"
    owner: root
    group: root
    mode: "0644"

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ k8s_kernel_modules }}"

- name: Set up required sysctl.d params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.d/kubernetes.conf"
    reload: true
  with_items: "{{ k8s_sysctl_variables }}"
