- name: Create kubeadm join token for worker node
  shell: |
    {{ kubeadm }} token create --print-join-command
  register: kubeadm_join_command_raw
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  run_once: true

- name: Set kubeadm join command
  set_fact:
    kubeadm_join_command: "{{ kubeadm_join_command_raw.stdout }}"
  when: kubeadm_join_command is not defined

- name: Check if node is joined to control-plane
  stat:
    path: "{{ kubernetes_conf_dir }}/kubelet.conf"
  register: kubelet_conf_st

- name: Join worker node to control-plane
  shell: |
    {{ kubernetes_bin_dir }}/{{ kubeadm_join_command }}
  when: kubelet_conf_st.stat.exists == False
