---
- name: Set nginx manifest directory
  ansible.builtin.set_fact:
    nginx_manifest_dir: "{{ k8s_conf_dir }}/applications/nginx"
    nginx_patch_files: "{{ nginx_merge_patches | map(attribute='name') }}"

- name: Create manifest directory for nginx
  ansible.builtin.file:
    path: "{{ nginx_manifest_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download nginx manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ nginx_version }}/deploy/static/provider/baremetal/deploy.yaml
    dest: "{{ nginx_manifest_dir }}/nginx.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Create patches directory
  ansible.builtin.file:
    path: "{{ nginx_manifest_dir }}/patches"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Capture existing patch files
  ansible.builtin.shell: >
    ls -1 {{ nginx_manifest_dir }}/patches
  register: existing_patch_files
  changed_when: false

- name: Remove patches that are not listed
  ansible.builtin.file:
    path: "{{ nginx_manifest_dir }}/patches/{{ item }}"
    state: absent
  with_items: "{{ existing_patch_files }}"
  when: item not in nginx_patch_files
  register: patches_delete

- name: Ensure wanted patches exist on node
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ nginx_manifest_dir }}/patches/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ nginx_merge_patches }}"
  register: patches_update

- name: Create kustomization file
  ansible.builtin.template:
    src: "kustomization.yaml.j2"
    dest: "{{ nginx_manifest_dir }}/kustomization.yaml"
    owner: root
    group: root
    mode: "0644"

- name: Apply nginx manifest
  ansible.builtin.shell: >
    {{ kubectl }} apply -k {{ nginx_manifest_dir }}
  changed_when: false
