---
- name: Set nginx manifest directory
  ansible.builtin.set_fact:
    nginx_manifest_dir: "{{ k8s_conf_dir }}/applications/nginx"

- name: Create manifest directory for nginx
  ansible.builtin.file:
    path: "{{ nginx_manifest_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download nginx manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ nginx_version }}/deploy/static/provider/baremetal/deploy.yaml
    dest: "{{ nginx_manifest_dir }}/nginx.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Copy patches for manifest
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ nginx_manifest_dir }}/{{ item.name }}.yaml"
  with_items: "{{ nginx_merge_patches }}"
  when: nginx_merge_patches is defined

- name: Create kustomization file
  ansible.builtin.template:
    src: "kustomization.yaml.j2"
    dest: "{{ nginx_manifest_dir }}/kustomization.yaml"

- name: Apply nginx manifest
  ansible.builtin.shell: >
    {{ kubectl }} apply -k {{ nginx_manifest_dir }}
  changed_when: false
