---
- name: Create conf file to load required kernel modules on boot
  ansible.builtin.template:
    src: "crio_kernel_modules.conf.j2"
    dest: "/etc/modules-load.d/crio.conf"
    owner: root
    group: root
    mode: "644"

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ crio_kernel_modules }}"

- name: Set up required sysctl.d params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.d/99-crio.conf"
    reload: true
  with_items: "{{ crio_sysctl_variables }}"

- name: Install CRI-O
  ansible.builtin.include_tasks: install.yaml

- name: Start and enable CRI-O
  ansible.builtin.systemd:
    name: "crio"
    state: started
    enabled: true
    daemon_reload: true
