---
- name: Assert that Calico version is defined
  ansible.builtin.assert:
    that: calico_version is defined
    fail_msg: Variable 'calico_version' has to be defined
    quiet: true

- name: Get deployed Calico Deployment image
  ansible.builtin.shell: >
    {{ kubectl }} -n kube-system get deployment/calico-kube-controllers
    --ignore-not-found
    -o jsonpath="{$.spec.template.spec.containers[0].image}"
  changed_when: false
  register: calico_deployment

- name: Get deployed Calico DaemonSet image
  ansible.builtin.shell: >
    {{ kubectl }} -n kube-system get daemonset/calico-node
    --ignore-not-found
    -o jsonpath="{$.spec.template.spec.containers[0].image}"
  changed_when: false
  register: calico_daemon_set

- name: Determine Calico versions
  ansible.builtin.set_fact:
    calico_deployment_version: "{{ calico_deployment.stdout | regex_replace('.*?:v') }}"
    calico_daemon_set_version: "{{ calico_daemon_set.stdout | regex_replace('.*?:v') }}"

- name: Print current Calico resources versions
  ansible.builtin.debug:
    msg:
      - "calico-kube-conrollers={{ calico_deployment_version }}"
      - "calico-node={{ calico_daemon_set_version }}"

- name: Include install tasks
  ansible.builtin.include_tasks: install.yaml

- name: Check Deployment calico-kube-controllers rollout status
  ansible.builtin.shell: >
    {{ kubectl }} rollout status
    -n kube-system
    --timeout=5m
    deployment calico-kube-controllers
  changed_when: false

- name: Check DaemonSet calico-node rollout status
  ansible.builtin.shell: >
    {{ kubectl }} rollout status
    -n kube-system
    --timeout=10m
    daemonset calico-node
  changed_when: false
