crio_kernel_modules:
  - overlay
  - br_netfilter

crio_sysctl_variables:
  - name: net.bridge.bridge-nf-call-iptables
    value: "1"
  - name: net.ipv4.ip_forward
    value: "1"
  - name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
