- name: Set master host
  set_fact:
    control_plane_master: "{{ groups['k8s_control_plane'][0] }}"

- name: Print control-plane master node
  debug:
    var: control_plane_master

- name: Include tasks for control-plane master node
  include_tasks: master.yml
  when: inventory_hostname == control_plane_master

- name: Include tasks for other control-plane nodes
  include_tasks: secondary.yml
  when: inventory_hostname != control_plane_master
