- name: Check if cluster is already initalized
  stat:
    path: "{{ kubernetes_conf_dir }}/admin.conf"
  register: kubeadm_admin_conf

- name: Initalize cluster with kubeadm
  shell: >
    {{ kubeadm }} init 
    --control-plane-endpoint {{ kubernetes_control_plane_endpoint }}
    --upload-certs
  when: kubeadm_admin_conf.stat.exists == False
  register: kubeadm_init_result

- name: Debug init result
  debug:
    var: kubeadm_init_result

- name: Download calico manifest
  get_url:
    url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: "0440"

- name: Install network plugin
  shell: >
    {{ kubectl }} apply -f /tmp/calico.yaml
