---
- name: Check that all kube-system pods for control node are ready
  ansible.builtin.shell: >
    {{ kubectl }} wait
    -n kube-system
    --timeout 5m
    --for condition=Ready
    -l tier=control-plane
    --field-selector spec.nodeName={{ ansible_hostname }}
    pods
  changed_when: false
  register: health_check_result
  retries: 3
  delay: 5
  until: health_check_result is not failed