---
- name: Check that all kube-system pods for control node are ready
  ansible.builtin.shell: >
    {{ kubectl }} wait
    -n kube-system
    --timeout 5m
    --for condition=Ready
    --field-selector spec.nodeName={{ ansible_hostname }}
    pods
  changed_when: false
