---
- name: Initalize cluster with kubeadm
  ansible.builtin.shell: >
    {{ kubeadm }} init
    --control-plane-endpoint {{ k8s_control_plane_endpoint }}
    --pod-network-cidr {{ k8s_pod_network_cidr }}
    --apiserver-advertise-address {{ ansible_facts[k8s_ethernet_interface]['ipv4']['address'] }}
    {{ k8s_init_extra_options }}
  changed_when: false
  register: kubeadm_init_result

- name: Debug init result
  ansible.builtin.debug:
    var: kubeadm_init_result
