---
- name: Upload certificates
  ansible.builtin.shell: >
    {{ kubeadm }} init phase upload-certs --upload-certs
  changed_when: false
  run_once: true
  delegate_to: "{{ k8s_control_first_node }}"
  register: upload_certs_output

- name: Create kubeadm join token
  ansible.builtin.shell: >
    {{ kubeadm }} token create --print-join-command
  changed_when: false
  run_once: true
  delegate_to: "{{ k8s_control_first_node }}"
  register: token_create_output

- name: Parse options for joining control plane node
  ansible.builtin.set_fact:
    token: "{{ token_create_output.stdout | regex_search('--token (.*?)(\\s|$)', '\\1') | first }}"
    discovery_token_ca_cert_hash: "{{ token_create_output.stdout | regex_search('--discovery-token-ca-cert-hash (.*?)(\\s|$)', '\\1') | first }}"
    certificate_key: "{{ upload_certs_output.stdout_lines | last }}"

- name: Join control plane node to cluster
  ansible.builtin.shell: >
    {{ kubeadm }} join {{ k8s_control_plane_endpoint }}
    --token {{ token }}
    --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }}
    --control-plane
    --certificate-key {{ certificate_key }}
    --apiserver-advertise-address {{ ansible_facts[k8s_ethernet_interface]['ipv4']['address'] }}
  changed_when: false
