---
- name: Check if admin.conf exists
  ansible.builtin.stat:
    path: "{{ k8s_conf_dir }}/admin.conf"
  register: admin_conf


- name: Include tasks for initializing control plane on first node
  include_tasks: init.yaml
  when:
    - not admin_conf.stat.exists
    - inventory_hostname == k8s_control_first_node

- name: Include tasks for joining addition control plane node
  include_tasks: join.yaml
  when:
    - not admin_conf.stat.exists
    - inventory_hostname != k8s_control_first_node

- name: Include manifest patches_update
  ansible.builtin.include_tasks: patches.yaml

- name: Include control plane node health checks
  ansible.builtin.include_tasks: health.yaml
