---
- name: Check if node is joined
  ansible.builtin.stat:
    path: "{{ k8s_conf_dir }}/kubelet.conf"
  register: kubelet_conf

- name: Include tasks for joining worker node
  ansible.builtin.include_tasks: join.yaml
  when: not kubelet_conf.stat.exists

- name: Include tasks for worker node health check
  ansible.builtin.include_tasks: health.yaml
