# Versions
crio_version: "1.23.3"
k8s_version: "1.23.5"
calico_version: "3.22"
nginx_version: "1.1.3"

# First node name where kubeadm init is run
k8s_control_first_node: "master1"
# The endpoint for the cluster control plane
k8s_control_plane_endpoint: "192.168.56.5:6443"
# k8s_ethernet_interface: "eth1"

# Kustomize merge patches for Calico default manifest
calico_merge_patches:
  - name: "calico-patch1.yaml"
    path: "files/calico/calico-patch1.yaml"

# Kustomize merge patches for Ingress-NGINX default manifest
nginx_merge_patches:
  - name: "nginx-patch1.yaml"
    path: "files/nginx/nginx-patch1.yaml"

# Patches provided for control plane components, see kubeadm --patches argument
k8s_control_static_manifest_patches:
  - name: "kube-apiserver01+merge.yaml" # target[suffix][+patchtype].extension
    path: "files/manifests/kube-apiserver01+merge.yaml" # local path to patch
